algoritmo "Operadores-Logicos-e-Relacionais"

var
//operadores relacionais
   A, B, C: Inteiro

inicio

//operadores relacionais
      A<-2
      B<-3
      C<-5
      
      Escreval (A>B)
      Escreval (A=B)
      Escreval (A<>B)
      Escreval (A>=2)
      Escreval (C=A+B)
      Escreval (C>=B^A)
      
//operadores lógicos
      Escreva(verdadeiro e falso)
      Escreva((A=B) ou (C>A))
fimalgoritmo
